const express = require('express');
const validate = require('../../middlewares/validate');
const authValidation = require('../../validations/auth.validation');
const kmarticalController = require('../../controllers/kmartical.controller');
const router = express.Router();

router.post('/add', kmarticalController.addKMArtical);
router.post('/addevent', kmarticalController.addKMEvent);
router.post('/eventList', kmarticalController.KMEventList);
router.post('/attachment', kmarticalController.upload, kmarticalController.createArticleAttachment);
router.post('/uploadattachment', kmarticalController.uploadArticleAttachment);
router.post('/eventattachment', kmarticalController.eventUpload, kmarticalController.createEventAttachment);
router.post('/ckEditor/attachment', kmarticalController.ckEditorUpload, kmarticalController.ckEditorImaPath);
router.post('/search', kmarticalController.searchKMArtical);
router.post('/addlike', kmarticalController.addLikeByArtical);
router.post('/addcomment', kmarticalController.addCommentByArtical);
router.post('/dislike', kmarticalController.disLikeArtical);
router.post('/deletecomment', kmarticalController.deleteArticalComment);
router.post('/topContributors', kmarticalController.topContributors);
router.post('/latestArticle', kmarticalController.latestArtical);
router.post('/latestArticlenew', kmarticalController.latestArticalnew);
router.post('/articleList', kmarticalController.articleList);
router.post('/myarticle', kmarticalController.myarticle);
router.post('/kmarticleunpublished', kmarticalController.kmarticleunpublished);
router.post('/kmarticleMyReviewList', kmarticalController.kmarticleMyReviewList);
router.post('/kmarticledashboard', kmarticalController.kmarticledashboard);
router.post('/kmdashboard', kmarticalController.kmdashboard);
router.post('/kmdashboardContributionSummary', kmarticalController.kmdashboardContributionSummary);
router.post('/kmdashboardcasestudies', kmarticalController.kmdashboardCaseStudies);
router.post('/searchcount', kmarticalController.searchCount);
router.get('/totalsearchcount', kmarticalController.GetsearchCount);
router.get('/registereduserscount', kmarticalController.TotalRegisteredUsersCount);
router.post('/kmdashboardclientcategory', kmarticalController.kmdashboardClientCategory);
router.post('/articlecomments', kmarticalController.articlecomments);
router.post('/article_getbyid', kmarticalController.articlegeybyid);
router.get('/getEventById/:id', kmarticalController.eventgetById);
router.post('/article_approve', kmarticalController.article_approve);
router.delete('/attachment/delete/:id', kmarticalController.deleteAttachment);
router.delete('/attachment/event/delete/:id', kmarticalController.deleteEventAttachment);
router.post('/article_revision', kmarticalController.articleRevisionApply);
router.get('/article_revision_get/:id', kmarticalController.articleRevisionGet);
router.post('/article_revision_set', kmarticalController.articleRevisionSet);
router.post('/cancel_event', kmarticalController.cancelEvent);
router.post('/event_register', kmarticalController.eventRegister);
router.get('/event_list_register/:id', kmarticalController.eventRegisterForList);
router.post('/populalr_articlelist', kmarticalController.getPopularArticleList);
router.post('/review_approve_apply', kmarticalController.reviewApproveApply);
router.post('/review_approve_list', kmarticalController.reviewApproveList);
router.post('/post_upvotes', kmarticalController.UpvotesCount);
router.get('/getupvotecount', kmarticalController.GetUpvotesCount);
router.get('/getdownvotecount', kmarticalController.GetDownvotesCount);
router.post('/post_downvotes', kmarticalController.DownvotesCount);
router.get('/getsuccsearchcount', kmarticalController.GetsearchSuccCount);
router.post('/post_searchsucccount', kmarticalController.searchSuccCount);
router.get('/article_revisionlist/:id', kmarticalController.RevisionArticlesGetByUserId);
router.post('/kmarticle_get_up_down_vote', kmarticalController.getUpandDownVotes);
router.post('/get_usersdata_barchart', kmarticalController.GetUsersDataBarChart);
router.post('/kmarticle_up_down_vote', kmarticalController.articleUPandDownVoteApply);
router.post('/kmarticle_up_down_vote_revert', kmarticalController.articleUPandDownVoteRevert);

module.exports = router;
